- name: Test htpasswd module from community.general
  hosts: rh95-ug.example.com
  gather_facts: false
  tasks:
    - name: Create htpasswd entry
      community.general.htpasswd:
        path: /tmp/.htpasswd
        name: testuser
        password: testpass
