---
- name: Test community.crypto module
  hosts: rh95-ug.example.com
  gather_facts: false
  tasks:
    - name: Generate a private key
      community.crypto.openssl_privatekey:
        path: /tmp/testkey.pem
        size: 2048
